
### Data Handler ###
dataType: "simulated"
pathDuration: 3
pathRadius: 4
numSamples: 100
numStates: 4
stateTransitionWidth: 1

# Simulated Motion Noise in world frame
worldMotionNoise: [
  [ 
    [0, 0, 0], # velocity mean
    [0, 0, 0], # velocity variance
  ],         
  [ 
    [0, 0, 0], # orienation mean
    [0, 0, 0], # orienation variance
  ],
]

# Simulated Motion Noise in robot frame
robotMotionNoise: [
  [ 
    [.001, .001, 0], # velocity mean
    [0, 0, 0], # velocity variance
  ],         
  [ 
    [0, 0, 0], # orienation mean
    [0, 0, .0005], # orienation variance
  ],
]

# Simulated Sensor Noise in robot frame
sensorNoise: [
  [ 
    [0, 0, 0], # gyroscope mean
    [0, 0, .5], # gyroscope variance - Note: datasheet says .05 deg/sec, this is in (radians/sec)^2
  ],         
  [ 
    [0, 0, 0], # accelerometer mean
    [20.0397832, 20.0397832, 0], # accelerometer variance - Note: datasheet says PSD = 400ug/sqrt(Hz) .. Variance ~2PSD*Bandlimit (bandlimit is 260Hz)
  ],
  [ 
    [0], # rssi mean
    [10], # rssi variance
  ],  
]

# sensorNoise: [
#   [ 
#     [0, 0, 0], # gyroscope mean
#     [0, 0, 0], # gyroscope variance - Note: datasheet says .05 deg/sec, this is in (radians/sec)^2
#   ],         
#   [ 
#     [0, 0, 0], # accelerometer mean
#     [0, 0, 0], # accelerometer variance - Note: datasheet says PSD = 400ug/sqrt(Hz) .. Variance ~2PSD*Bandlimit (bandlimit is 260Hz)
#   ],
#   [ 
#     [0], # rssi mean
#     [0], # rssi variance
#   ],  
# ]

# dataType: "log"
# # dataSensorValueLog: "../shubhamCircle4.log"
# # dataSensorValueLog: "../deskCircle1.log"
# # dataSensorValueLog: "../mocap_20ms_1.log"
# dataSensorValueLog: "../sampleData1.log"

# computeBiasAndMeanSamples: 0

### Robot System ###
filter_name: "TestFilter" 
numParticles: 100
# numParticles: 1
wifiErrorCovariance: 10

alphas_sqrt: [
  0,  0,  0, 
  0,  0,  0
]

# initial_state_vals: [
#   0, 0,   0, # orientation
#   0, 0,   0, # velocity
#   5, 6.5, 0  # position 
# ]

initial_state_vals: [
  0, 0,   0, # orientation
  0, 0,   0, # velocity
  10, 4, 0  # position 
]

# initial_state_vals: [
#   0, 0,  0, # orientation
#   0, 0,  0, # velocity
#   0, 0,  0  # position 
# ]

# Note: in sqrt values
initial_state_variance: [
  0, 0, .1, # orientation
  1, 1, 0, # velocity
  1, 1, 0  # position 
] 

### path publisher ###
frameId: "map"
gt_path_topic: "groundtruth/path"
command_path_topic: "command/path"
ellipse_topic: "robot_state/nonlinear_cov"
pose_topic: "robot_state/pose"
path_topic: "robot_state/path"

particlePathTopic: "particlePath"
integrationPathTopic: "integrationPath"
