
### Data Handler ###
dataType: "simulated"
pathDuration: 3
pathRadius: 4
numSamples: 100
numStates: 4
stateTransitionWidth: 1

# Simulated Motion Noise in world frame
worldMotionNoise: [
  [ 
    [0, 0, 0], # velocity mean
    [0, 0, 0], # velocity variance
  ],         
  [ 
    [0, 0, 0], # orienation mean
    [0, 0, 0], # orienation variance
  ],
]

# Simulated Motion Noise in robot frame
robotMotionNoise: [
  [ 
    [0, 0, 0],       # velocity mean
    [.001, .001, .001], # velocity variance
  ],         
  [ 
    [0, 0, 0], # orienation mean
    [.0005, .0005, .0005], # orienation variance
  ],
]

# # Simulated Sensor Noise in robot frame
# # Note: These values yield good results with simulation data
# sensorNoise: [
#   [ 
#     [-0.5, -0.5, -0.5], # gyroscope mean
#     [.05, .05, .05], # gyroscope variance - Note: datasheet says .05 deg/sec, this is in (radians/sec)^2
#   ],         
#   [ 
#     [-5, -10, -8], # accelerometer mean
#     [15, 15, 15], # accelerometer variance - Note: datasheet says PSD = 400ug/sqrt(Hz) .. Variance ~2PSD*Bandlimit (bandlimit is 260Hz)
#   ],
#   [ 
#     [0], # rssi mean
#     [20], # rssi variance
#   ],  
# ]

# Mocap sensor noise
sensorNoise: [
  [ 
    [0, 0, 0], # gyroscope mean
    [0, 0, .12], # gyroscope variance - Note: datasheet says .05 deg/sec, this is in (radians/sec)^2
  ],         
  [ 
    # [-0.5, 0.3, 0], # acceerometer mean
    # [0, 0, 0], # acceerometer mean
    [0.35, -0.4, 0], # acceerometer mean
    [17, 17, 0], # accelerometer variance - Note: datasheet says PSD = 400ug/sqrt(Hz) .. Variance ~2PSD*Bandlimit (bandlimit is 260Hz)
  ],
  [ 
    [0], # rssi mean
    [5.5], # rssi variance
  ],  
]

dataType: "log"

dataStartOffset: 17
# dataStartOffset: 7
# dataStartOffset: 4
biasSampleOffset: 0
dataMocapTimeOffset: .85 # NOTE: TUNED BY HAND WITH GYRO
dataSensorValueLog: "../mocap_20ms_1.log"
dataMocapLog: "../20ms_start479818817.csv"
wifiMap: "wifiMap.png.txt"
wifiMapResolution: .1
wifiMapOrigin: [-2.5, -2.5, 0]
computeInitialStateSamples: 3
computeBiasSamples: 300
# computeBiasSamples: 180
# computeBiasSamples: 20
# computeBiasSamples: 5
# computeBiasSamples: 1

# # TODO: fine tune this once we add rviz update rate
# dataMocapTimeOffset: -0.5
# dataSensorValueLog: "../mocap_6ms_1.log"
# dataMocapLog: "../6ms_start2939061327.csv"

# dataMocapTimeOffset: 0
# dataSensorValueLog: "../mocap3dBlocker_6ms_1.log"
# dataMocapLog: "../6ms_obstacle_start1280026682.csv"

# dataMocapTimeOffset: 0
# dataSensorValueLog: "../mocap3d_6ms_1.log"
# dataMocapLog: "../6ms_3D_start691620221.csv"


# dataSensorValueLog: "../sampleData1.log"
# computeBiasSamples: 10
# computeInitialStateSamples: 10

# dataSensorValueLog: "../shubhamCircle4.log"
# dataSensorValueLog: "../deskCircle1.log"

# TODO: Add projectZAxis
constrainZAxis: true
realtimeSim: false
rvizFPSLimit: 5


### Robot System ###
filter_name: "TestFilter" 
numParticles: 50
wifiCovariance: 5.5

alphas_sqrt: [
  0,  0,  0, 
  0,  0,  0
]

# # Note: For simulation data
# initial_state_vals: [
#   0, 0,   0, # orientation
#   0, 0,   0, # velocity
#   21, 12, 0  # position 
# ]

initial_state_vals: [
  0,  0,  0, # orientation
  0,  0,  0, # velocity
  0,  0,  0  # position 
]

# Note: in sqrt values
initial_state_variance: [
  0, 0,  .6, # orientation
  13, 13, 0, # velocity
  2.5, 2.5, 0  # position 
] 

### path publisher ###
frameId: "map"
gt_path_topic: "groundtruth/path"
command_path_topic: "command/path"
ellipse_topic: "robot_state/nonlinear_cov"
pose_topic: "robot_state/pose"
path_topic: "robot_state/path"

particlePathTopic: "particlePath"
integrationPathTopic: "integrationPath"
