

### Data Handler ###
dataType: "simulated"
# dataType: "log"
dataSensorValueLog: "../sampleData5.log"

### Robot System ###
filter_name: "TestFilter"      # name of the filter 

# motion noise (in odometry space, see Table 5.5, p.134 in book).
# alphas_sqrt: [
#   0.00025,  0.00005,  0.0025, 
#   0.0005,   0.0025,   0.0005
# ]  
alphas_sqrt: [
  0,  0,  0, 
  0,  0,  0
]
# sensor noise
beta: 5 # approx 5 deg.

# init state
deltaT: 0.1

initial_state_vals: [
  0, 0,  0, # orientation
  0, 0,  0, # velocity
  0, 0,  0  # position 
]

# Note: in sqrt values
initial_state_variance: [
  1, 1, 1, # orientation
  1, 1, 1, # velocity
  1, 1, 1  # position 
] 

### path publisher ###
path_frame_id: "map"
gt_path_topic: "groundtruth/path"
command_path_topic: "command/path"
ellipse_topic: "robot_state/nonlinear_cov"
pose_topic: "robot_state/pose"
path_topic: "robot_state/path"
